os: linux
language: python
python: "3.7"

install:
  - pip install -U platformio

matrix:
  fast_finish: true
  include:
    - env: BOARD=nodemcuv2
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=nanoatmega328
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=nodemcu-32s
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=d1_mini
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=sparkfun_samd21_mini_usb
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=sparkfun_samd21_dev_usb
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
    - env: BOARD=zero
      script:
        - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board $BOARD
